services:
  postgres:
    image: postgres:17
    container_name: App_Login
    restart: unless-stopped
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: App_Login
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: